# Generated by Django 4.2.2 on 2024-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actors', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('genres', models.CharField(max_length=255)),
                ('seasons', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('platform', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('avg_episode_time', models.IntegerField()),
                ('actors', models.CharField(max_length=255)),
            ],
        ),
        
    ]
