# Generated by Django 4.2.2 on 2024-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='show',
            old_name='avg_episode_time',
            new_name='average_episode_duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='show',
            name='actors',
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='myapp.actor'),
        ),
        migrations.AddField(
            model_name='show',
            name='actors',
            field=models.ManyToManyField(related_name='shows', to='myapp.actor'),
        ),
    ]
