# Generated by Django 4.2.2 on 2024-07-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_show_episodes_movie_image_show_image_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('watched', 'moviewatched'), ('not_watched', 'movienotwatched')], default='not_watched', max_length=20),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('completed', 'show is done'), ('watching', 'still watching'), ('not_watched', 'not started')], default='not_watched', max_length=20),
        ),
    ]
