# Generated by Django 4.2.2 on 2024-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='status',
            field=models.CharField(choices=[('watched', 'Watched'), ('not_watched', 'Not Watched')], default='not_watched', max_length=20),
        ),
    ]
