# Generated by Django 4.2.2 on 2024-07-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_movie_imdb_rating_alter_movie_runtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_rating',
        ),
    ]
