# Generated by Django 4.2.2 on 2024-07-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
