# Generated by Django 4.2.2 on 2024-07-21 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='air_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
