# Generated by Django 4.2.2 on 2024-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_movie_air_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='imdb_rating',
            field=models.FloatField(default=1),
        ),
    ]
