# Generated by Django 4.2.2 on 2024-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_show_imdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='last_watched',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_watched',
            field=models.DateField(null=True, blank=True),
        ),
    ]
