# Generated by Django 4.2.2 on 2024-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_episode_last_watched_movie_last_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='last_watched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='last_watched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
